package com.sulaiman.yuyu;


import java.util.ArrayList;

public class SultanData {
    public static String[][] data = new String[][]{
            {"Osman Ghazi", "1299 ‒ 1323", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Osman_Gazi2.jpg/200px-Osman_Gazi2.jpg","Malhun Hatun, Rabia Bala Hatun","Osman I atau Osman Ghazi (Turki Utsmaniyah: عثمان غازى, Osmān Ġāzī; meninggal 1323/4[2]) adalah bapak dari Wangsa Utsmaniyah dan merupakan pemimpin pertama dari Negara Utsmaniyah, yang di masanya masih berupa kadipaten kecil. Ia mewarisi jabatan ayahnya sebagai adipati (bey) di bawah Kesultanan Seljuk. Saat kesultanan tersebut mengalami gonjang-ganjing, Osman memerdekakan diri dan memerintah kadipaten berdaulat itu sampai akhir hayatnya pada 1323 atau 1324. Sepeninggalnya, keturunannya menggunakan namanya sebagai nama dinasti dan negaranya (nama dinasti dan negara tersebut dieja menjadi 'Utsmani' atau 'Utsmaniyah' dalam bahasa Arab dan Indonesia dan menjadi 'Ottoman' dalam ejaan barat). "},
            {"Orhan Ghazi", "1323 ‒ Maret 1362", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Orhan_Gazi.jpg/220px-Orhan_Gazi.jpg","Nilüfer Hatun, Asporça Hatun, Theodora Kantakouzene Hatun, Eftandise Hatun","Orhan Ghazi (Turki Utsmaniyah: اورخان غازی, Orhan Ghazi; mangkat pada Maret 1362) adalah penguasa Negara Utsmaniyah kedua yang berkuasa pada 1323/4 sampai 1362. Pada masa awal pemerintahannya, putra dari Osman I ini memusatkan perhatiannya pada penaklukan barat laut wilayah Anatolia yang berada dalam kendali Kekaisaran Romawi Timur. Orhan berhasil memenangkan beberapa pertempuran yang terjadi antara pihaknya dan Romawi, juga mengambil alih kepemimpinan beberapa kota. Hal ini masih ditambah dengan perang saudara di dalam Kekaisaran Romawi Timur sendiri, juga Ioannes V Palaiologos yang menjadi Kaisar Romawi Timur saat masih sangat belia (sembilan tahun), menjadikan pihak Romawi Timur semakin sulit saat berhadapan dengan Orhan. "},
            {"Murad I", "Maret 1362 – 14 Juni 1389", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Murat_H%C3%BCdavendigar.jpg/220px-Murat_H%C3%BCdavendigar.jpg","Gülçiçek Hatun, Thamara Hatun, Paşa Melek Hatun","Murad I (bahasa Turki: I. Murat, Turki Utsmaniyah: مراد اول; lahir di Söğüt atau Bursa, 29 Juni 1326 – meninggal di Kosovo, 15 Juni 1389 pada umur 62 tahun) adalah pemimpin Utsmani ketiga dan berkuasa sepeninggal ayahnya antara tahun 1361 hingga 1389. Ia adalah putra Orhan dan Nilüfer Hatun. Murad I dijuluki Hüdavendigâr, yang berasal dari bahasa Persia: Khodāvandgār (خداوندگار), yang berarti \"yang disayangi Tuhan\". "},
            {"Bayezid I ", "16 Juni 1389 ‒ 20 Juli 1402", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Y%C4%B1ld%C4%B1r%C4%B1m_I._Bayezit.JPG/220px-Y%C4%B1ld%C4%B1r%C4%B1m_I._Bayezit.JPG","Devlet Hatun, Devletşah Hatun, Hafsa Hatun, Despina (Olivera) Hatun, Maria Hatun","Bayezid I (Turki Utsmaniyah: بايزيد اول, bahasa Turki: II. Beyazıt; Edirne, 1360 - Akşehir, 8 Maret 1403) adalah Sultan Utsmaniyah yang berkuasa antara tahun 1389-1402. Ia adalah putra Murad I[1][2] dan Gülçiçek Hatun.Bayezid dikenal sebagai sosok yang sangat pemberani, cerdas, murah hati, dan demikian ambisi untuk melakukan perluasan wilayah Utsmani. Oleh karena itulah dia menaruh perhatian besar pada masalah kemiliteran dan berencana menaklukkan negara-negara Kristen di Anatolia. Hanya dalam jangka waktu setahun, negara-negara itu telah berada di bawah kekuasaan pemerintahan Utsmani. Dalam geraknya Bayezid I digambarkan laksana kilat di antara dua front Balkan dan Anatolia. Oleh karena itu, dia diberi gelar \"Sang Kilat\" (bahasa Turki: Yıldırım). Dia juga menghimpun satu dari pasukan terbesar dan terbanyak di masa itu guna melakukan pengepungan terhadap Konstantinopel, meski misi tersebut pada akhirnya tidak berhasil. "},
            {"Mehmed Çelebi", "5 Juli 1413 – 26 Mei 1421", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/%C3%87elebi_Mehmet.jpg/220px-%C3%87elebi_Mehmet.jpg","Emine Hatun, Şehzade Hatun, Kumru Hatun","Mehmed I Çelebi (Turki Utsmaniyah: چلبی محمد; Bursa, 1390 - Edirne, 26 Mei 1421) adalah Sultan Utsmaniyah yang berkuasa antara tahun 1413-1421. Dia menjadi sultan tunggal Negara Utsmani setelah mengalahkan saudara-saudaranya dalam perebutan takhta selama sebelas tahun sepeninggalnya ditawannya ayah mereka, Sultan Bayezid I oleh Timur Lenk. Atas capaiannya, Mehmed kerap dijuluki sebagai pendiri kedua Utsmaniyah. "},
            {"Murad II", "26 Mei 1421 – Agustus 1444", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/II._Murat.jpg/220px-II._Murat.jpg","Yeni Hatun, Hatice Halime Hatun, Hüma Hatun, Mara Branković Hatun","Murad II (Juni 1404 – 3 Februari 1451) (bahasa Turki Utsmani: مراد ثانى Murād-ı sānī, bahasa Turki:II. Murat) adalah Sultan Utsmaniyah dari 1421 hingga 1451 (kecuali dari masa antara 1444 hingga 1446). Pemerintahan Murad II ditandai dengan peperangan panjang melawan para bangsawan Kristen di Balkan dan berbagai kadipaten Turki di Anatolia, konflik yang berlangsung selama 25 tahun. Ia besar di Amasya dan naik takhta setelah kematian ayahandanya. "},
            {"Muhammad al-Fatih", "Agustus 1444 – September 1446", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Gentile_Bellini_003.jpg/220px-Gentile_Bellini_003.jpg","Gülbahar Hatun, Gülşah Hatun, Sittişah Hatun, Hatice Hatun, Çiçek Hatun","Mehmed II (Turki Utsmaniyah: محمد ثانى, Meḥmet-i sānī; Turki: II. Mehmet; 30 Maret 1432 – 3 Mei 1481), juga dikenal secara luas dengan Muhammad al-Fatih (محمد الفاتح, Fatih Sultan Mehmed) merupakan penguasa Utsmani ketujuh dan berkuasa pada 1444 – 1446 dan 1451 – 1481. Capaiannya yang paling dikenal luas adalah penaklukan Konstantinopel pada tahun 1453 yang mengakhiri riwayat Kekaisaran Romawi Timur, menjadikannya mendapat julukan 'Sang Penakluk' (الفاتح, el-Fatih). Mehmed dikenal sebagai pemimpin yang cakap dan mempunyai kepakaran dalam bidang ketentaraan, ilmu pengetahuan, matematika, dan menguasai enam bahasa saat berumur 21 tahun. Dia dikenal sebagai pahlawan di Turki maupun dunia Islam secara luas. Dalam sejarah Islam, Mehmed dikenal sebagai salah seorang pemimpin yang hebat sebagaimana Sultan Shalahuddin Al-Ayyubi (pahlawan Islam dalam perang Salib) dan Sultan Saifuddin Mahmud Al-Qutuz (pahlawan Islam dalam peperangan di 'Ain Al-Jalut melawan tentara Mongol). Di pemerintahan, Mehmed lebih memilih para pejabat tinggi dari latar belakang devşirme daripada mereka yang berasal dari keluarga bangsawan, menjadikan kendali negara benar-benar terpusat pada sultan. "},
            {"Bayezid II", "22 Mei 1481 – 24 April 1512", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sultan_II._Bayezit.JPG/220px-Sultan_II._Bayezit.JPG","Nigar Hatun, Şirin Hatun, Gülruh Hatun, Bülbül Hatun, Hüsnüşah Hatun, Ayşe Gülbahar Hatun, Muhtereme Hatun","Bayezid II (Turki Utsmaniyah: بايزيد ثانى Bāyezīd-i s̱ānī, Turki: II. Bayezid atau II. Beyazıt; lahir, 3 Desember 1447, wafat, 26 Mei 1512) adalah penguasa Utsmani kedelapan yang berkuasa pada 1481–1512. Dia adalah anak tertua dari Mehmed II.[3] Bayezid dikenal akan kebijakannya memberikan suaka kepada umat Yahudi dan Muslim yang diusir dari Andalusia setelah Penaklukan Granada. Pada masa kekuasaannya, Utsmani terlibat perang dengan Mamluk dan Venesia, juga menyaksikan kebangkitan Wangsa Safawiyah di Persia yang menjadi pesaing berat Utsmani selama beberapa abad berikutnya. "},
            {"Selim I", "1517 – 22 September 1520", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Yavuz_Sultan_I._Selim_Han.jpg/220px-Yavuz_Sultan_I._Selim_Han.jpg","Ayşe Hatun, Hafsa Hatun","Selim I (Bahasa Turki Utsmaniyah: سليم اول, Bahasa Turki: Birinci Selim; 1470/1 – September 1520) adalah penguasa Utsmani kesembilan dan berkuasa pada tahun 1512 sampai 1520.[1] Watak dan kepribadiannya yang keras menjadikannya mendapat julukan Yavuz Sultan Selim (Yavuz sendiri dapat dimaknai dengan keras, teguh atau tegas "},
            {"Süleyman I", "1520–1566 (46 tahun)", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/EmperorSuleiman.jpg/220px-EmperorSuleiman.jpg","Mahidevran Sultan, Hurrem Sultan, Gülfem Hatun","Suleiman I (Turki Utsmaniyah: سليمان Suleymān, Turki Modern: Süleyman; 6 November 1494  – 5/6/7 September 1566) adalah sultan Turki Utsmaniyah ke-10 yang berkuasa dari tahun 1520 hingga 1566. Ia dikenal sebagai Suleiman yang Luar Biasa di Barat, dan pemberi hukum (bahasa Turki: Kanuni; Arab: القانونى\u200E, al‐Qānūnī) di Timur karena pencapaiannya dalam menyusun kembali sistem undang-undang Utsmaniyah. Ia merupakan tokoh penting pada Eropa abad ke-16. Suleiman memimpin tentara Utsmaniyah menaklukkan Belgrade, Rhodes, dan sebagian besar Hongaria sebelum berhasil dipukul mundur dalam Pengepungan Wina tahun 1529. Ia menganeksasi sebagian besar Timur Tengah dan Afrika Utara (hingga sejauh Aljazair di barat). Di bawah kekuasaannya, armada Utsmaniyah menguasai Laut Tengah, Merah, dan Teluk Persia. Dalam upayanya untuk memperkuat Utsmaniyah, Suleiman melancarkan reformasi legislatif yang berhubungan dengan masyarakat, pendidikan, perpajakan, dan hukum kriminal. Hukum kanunnya memperbaiki bentuk kekaisaran selama berabad-abad setelah kematiannya. Selain merupakan penyair dan tukang emas, ia juga menjadi pelindung budaya yang besar, hingga Utsmaniyah mencapai masa keemasan dalam bidang artistik, sastra, dan arsitektur.[4] Suleiman mampu menuturkan lima bahasa: Bahasa Turki Utsmaniyah, Arab, Serbia, Chagatai (dialek bahasa Turki dan berhubungan dengan Uighur), dan Persia. Suleiman menikahi seorang perempuan harem yang bernama Hürrem Sultan, meskipun tindakan ini melanggar tradisi Utsmaniyah. Putra mereka, Selim II, menggantikan Suleiman setelah berkuasa selama 46 tahun. "},
    };

    public static ArrayList<Sultan> getListData(){
        ArrayList<Sultan> list = new ArrayList<>();
        for (String[] aData : data) {
            Sultan sultan = new Sultan();
            sultan.setName(aData[0]);
            sultan.setFrom(aData[1]);
            sultan.setPhoto(aData[2]);
            sultan.setPasangan(aData[3]);
            sultan.setHidup(aData[4]);
            list.add(sultan);
        }
        return list;
    }
}
